In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn


In [6]:
data = pd.read_csv('mobile_prices.csv')

In [7]:
data.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [10]:
data["price_range"].value_counts()

1    500
2    500
3    500
0    500
Name: price_range, dtype: int64

In [12]:
data.isnull().sum()    

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [13]:
X = data.iloc[:, :-1].values
Y = data.iloc[:, -1].values

In [15]:
from sklearn.preprocessing import StandardScaler

X = StandardScaler().fit_transform(X)

In [16]:
X

array([[-0.90259726, -0.9900495 ,  0.83077942, ..., -1.78686097,
        -1.00601811,  0.98609664],
       [-0.49513857,  1.0100505 , -1.2530642 , ...,  0.55964063,
         0.99401789, -1.01409939],
       [-1.5376865 ,  1.0100505 , -1.2530642 , ...,  0.55964063,
         0.99401789, -1.01409939],
       ...,
       [ 1.53077336, -0.9900495 , -0.76274805, ...,  0.55964063,
         0.99401789, -1.01409939],
       [ 0.62252745, -0.9900495 , -0.76274805, ...,  0.55964063,
         0.99401789,  0.98609664],
       [-1.65833069,  1.0100505 ,  0.58562134, ...,  0.55964063,
         0.99401789,  0.98609664]])

In [17]:
Y

array([1, 2, 2, ..., 3, 0, 3])

In [18]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [23]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1600, 20)
(1600,)
(400, 20)
(400,)


In [25]:
from sklearn.svm import SVC

svclassfier = SVC(kernel="linear")
svclassfier.fit(x_train, y_train)

SVC(kernel='linear')

In [26]:
y_predict = svclassfier.predict(x_test)

In [27]:
y_predict

array([1, 3, 1, 0, 1, 1, 1, 1, 1, 3, 3, 1, 0, 0, 2, 3, 3, 0, 2, 3, 0, 3,
       0, 1, 3, 1, 1, 3, 2, 1, 2, 2, 3, 3, 3, 1, 1, 3, 2, 0, 2, 1, 2, 0,
       0, 2, 2, 3, 3, 1, 2, 0, 1, 0, 3, 2, 3, 3, 1, 2, 0, 3, 1, 3, 3, 1,
       3, 3, 3, 0, 3, 2, 3, 2, 2, 1, 1, 1, 3, 2, 3, 1, 2, 2, 1, 0, 1, 3,
       2, 2, 1, 1, 3, 2, 2, 2, 0, 3, 3, 3, 1, 3, 3, 2, 1, 1, 2, 3, 1, 3,
       1, 1, 2, 3, 0, 3, 1, 1, 3, 0, 0, 1, 1, 3, 0, 3, 3, 2, 0, 3, 3, 0,
       3, 0, 2, 2, 1, 2, 1, 0, 0, 1, 3, 0, 3, 3, 3, 3, 1, 1, 3, 1, 0, 1,
       0, 0, 2, 1, 2, 3, 1, 2, 3, 3, 0, 1, 1, 2, 0, 0, 2, 3, 0, 1, 3, 2,
       1, 1, 3, 3, 2, 1, 3, 2, 1, 2, 2, 2, 2, 1, 0, 2, 0, 1, 0, 1, 3, 1,
       0, 0, 3, 1, 3, 0, 2, 2, 0, 2, 1, 0, 3, 3, 3, 0, 2, 1, 3, 2, 3, 3,
       1, 1, 3, 1, 1, 2, 0, 1, 0, 3, 1, 3, 3, 0, 2, 2, 0, 0, 1, 1, 3, 3,
       0, 1, 3, 2, 2, 2, 0, 2, 2, 1, 3, 1, 1, 2, 1, 0, 1, 0, 1, 3, 2, 2,
       0, 3, 0, 3, 0, 1, 0, 3, 0, 3, 3, 3, 3, 0, 2, 1, 2, 3, 3, 1, 2, 2,
       1, 3, 3, 0, 0, 1, 0, 3, 3, 3, 1, 1, 1, 3, 0,

In [28]:
y_test

array([1, 3, 0, 0, 1, 1, 1, 1, 1, 3, 3, 1, 0, 0, 2, 3, 3, 0, 2, 3, 0, 3,
       0, 1, 3, 1, 1, 3, 2, 1, 2, 2, 3, 3, 3, 1, 1, 3, 2, 0, 2, 1, 2, 0,
       0, 2, 3, 3, 3, 1, 2, 0, 1, 0, 3, 2, 3, 3, 1, 2, 0, 3, 1, 3, 3, 1,
       3, 3, 3, 0, 3, 2, 3, 2, 2, 1, 1, 1, 3, 2, 3, 1, 2, 2, 1, 0, 1, 3,
       2, 2, 1, 1, 3, 2, 2, 2, 0, 3, 3, 3, 1, 3, 3, 2, 1, 1, 2, 2, 2, 3,
       1, 1, 2, 3, 0, 3, 1, 1, 3, 0, 0, 1, 1, 3, 0, 3, 3, 2, 0, 3, 3, 0,
       3, 0, 2, 2, 2, 2, 1, 0, 0, 1, 2, 0, 3, 3, 3, 3, 0, 1, 3, 1, 0, 1,
       0, 0, 1, 1, 2, 3, 1, 2, 3, 3, 0, 1, 1, 2, 0, 0, 2, 3, 0, 1, 2, 2,
       1, 1, 2, 3, 3, 0, 3, 1, 1, 2, 2, 2, 2, 1, 0, 2, 0, 1, 0, 1, 3, 1,
       1, 0, 3, 1, 3, 0, 2, 2, 0, 2, 1, 0, 3, 3, 3, 0, 2, 1, 3, 2, 3, 3,
       1, 1, 3, 1, 1, 2, 0, 1, 0, 3, 1, 3, 3, 0, 2, 2, 0, 0, 1, 1, 3, 3,
       0, 1, 3, 2, 2, 2, 0, 2, 2, 1, 3, 1, 1, 2, 1, 0, 1, 0, 1, 3, 2, 2,
       0, 3, 0, 3, 0, 1, 0, 3, 0, 3, 3, 3, 3, 0, 2, 1, 2, 3, 3, 1, 2, 2,
       1, 3, 3, 0, 0, 1, 0, 3, 3, 3, 1, 2, 1, 3, 0,

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy = accuracy_score(y_test, y_predict) * 100
print("accuracy", accuracy)

accuracy 95.25


In [31]:
pd.crosstab(y_test, y_predict)

col_0   0   1   2    3
row_0                 
0      89   4   0    0
1       1  98   2    0
2       0   4  81    6
3       0   0   2  113